### ISSUE TITLE
PFSENSE_LOG_DATA doesn't match vlan interfaces

### ISSUE THREAD

**Issue by mxc** [patrickjennings/logstash-pfsense#1]
Hi there,
I had to change the PFSENSE_LOG_DATA pattern so it would match interface names with a vlan such as re0.1. The pattern  %{WORD:iface} does not match properly so I changed it to %{DATA:iface} instead

PFSENSE_LOG_DATA (%{INT:rule}),(%{INT:sub_rule})?,,(%{INT:tracker}),(%{DATA:iface}),(%{WORD:reason}),(%{WORD:action}),(%{WORD:direction}),(%{INT:ip_ver}),

Seems to be working this side :)

**Comment by patrickjennings** [comment]
Thank you for making me aware of that.
