### ISSUE TITLE
Merge with opnsense-logstash-config

### ISSUE THREAD

**Issue by ypid** [patrickjennings/logstash-pfsense#4]
As a OPNsense user https://github.com/fabianfrz/opnsense-logstash-config, works better and I have not tested logstash-pfsense. I wonder if it might make sense to merge. I have reworked https://github.com/fabianfrz/opnsense-logstash-config to use integration testing so logstash-pfsense could be merged into this as well we could have a unified OPNsense/pfSense Logstash config.

**Comment by patrickjennings** [comment]
I have not looked into the OPNsense logs to know how similar they are with pfsense. It's a worthy project that would warrant its own dedicated repo would be my opinion.
